### ISSUE TITLE
Add custom events

### ISSUE THREAD

**Issue by mercuree** [luratic/TikTok#1]
It is possible to add custom Tiktok events with GTM triggers instead of using tiktok css/url rules.
Tiktok internally generates  js events that look like this (code inside sdk.js):
```html
<script>
    _taq.push({event_type:"button", event_pixel_id:"<pixel_id>", event_pixel_code:"<sdkid>", advertiser_id:"<advertiser_id>", data_type:4});
</script>
```
**event_pixel_id** and **advertiser_id** are optional and not required.
**event_pixel_code** is required and it is the same as sdkid.
**data_type** is how event is registered (4 = count each action as an individual event, 2 = count multiple actions as one event)
https://i.imgur.com/m8TgrNN.png
**event_type** can take values from this list:
```
format: 
Event name in Tiktok ads manager = js event name

Page View = view
User Registration = on_web_register
Product Details Page Browse = on_web_detail
Add to Cart = on_web_cart
Place an Order = on_web_order
Button Click = button
Online Consultation = phone
Button Click Consultation = phone_button
Phone Consultation = consult
Complete Payment = shopping
Button Click (Form) = form_button
Form Submission = form
Details Page Browse (Consultation) = phone_detail
Download Button Click = download_start
Details Page Browse (App DownLoaded) = download_button
Button Click (App Downloaded) = download_detail
Details Page Browse Form = form_detail
```
Considering that **event_pixel_id** and **advertiser_id** are optional, we can safely use this `_taq ` array queue at any time:
For example, we can send User Registration event like this:
```html
<script>
    window._taq = window._taq || [];
    _taq.push({event_type:"on_web_register", event_pixel_code:"BAA6DIV3QM8FN6J12JD0", data_type:4});
</script>
```
I think, this approach can be implemented within your gtm template.

**Comment by luratic-devs** [comment]
Sorry @mercuree we have this pending. Soon release.

**Comment by mercuree** [comment]
Tiktok changed his pixel, This approach is no longer relevant. That's why I closed the issue.

**Comment by luratic-devs** [comment]
Ok, Our update will be out shortly with the changes proposed by TikTok Ads
Many Thanks @mercuree for all.
